name: cargo-deny
on:
    push:
      paths-ignore:
        - "**.md"
    pull_request:
      paths-ignore:
        - "**.md"
  
jobs:
  cargo-deny:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        checks:
          - advisories
          - sources
          - bans

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'sources' }}

    steps:
    - uses: actions/checkout@v4
    - run: git config --global http.postBuffer 524288000
    - run: git config --global   http.sslVerify "false"
    - run: git submodule update --init --recursive --depth 1
    - run: bash sh_script/pre-build.sh
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}